#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p '' -width 18 -hide-scrollbar -line-padding 8 -padding 20 -lines 4 <<< "  Lock|  Logout|  Reboot|  Shutdown")"
            case "$MENU" in
                *Lock) i3lock -c 999999 -i Pictures/lock/lockkucing.png ;;
                *Logout) openbox --exit;;
                *Reboot) reboot ;;
                *Shutdown)  shutdown -h now
            esac
