#!/bin/bash

# Show the terminal colourscheme as blocks
# Inspired by u/dkeg
# Cheers! Addy

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

cat << EOF
 
 $f1█████$t$f2█████$t$f3█████$t$f4█████$t$f5█████$t$f6█████$t 
 $f1█████$t$f2█████$t$f3█████$t$f4█████$t$f5█████$t$f6█████$t 
 $f1█████$t$f2█████$t$f3█████$t$f4█████$t$f5█████$t$f6█████$t 
 $ft█████$t$ft█████$t$ft█████$t$ft█████$t$ft█████$t$ft█████$t 
 
EOF
